name: linux-test

on:
  push:
  pull_request:

jobs:
  pytest:
    runs-on: [self-hosted, ubuntu]
    steps:
    - uses: actions/checkout@v3
    - name: Build Docker
      run: |
        docker build --build-arg="PY_VERSION=3.10" --tag ablator-test .
    - name: Test with pytest CUDA
      run: |
        bash ./scripts/run_tests.sh
    - name: Test with pytest CPU
      run: |
        bash ./scripts/run_tests.sh --cpu
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./shared/coverage_cpu.xml,./shared/coverage_gpu.xml
