name: linux-test

on:
  push:
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        pip install -e .[dev] -v
    - name: Install SSH and generate keys
      run: |
        sudo apt-get update
        sudo apt-get install -y openssh-server
        sudo service ssh start
        ssh-keygen -t rsa -f ~/.ssh/id_rsa -q -N ""
        cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
        sudo apt-get install -y rsync
    - name: Test with pytest
      run: |
        pip install pytest
        pytest