name: mac-test

on:
  push:
  pull_request:

jobs:
  pytest:
    runs-on: [self-hosted, macOS]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Conda Python 3.10
        run: |
            conda remove -y --name test-env --all
            conda create -y -n test-env python=3.10
      - name: Install dependencies
        run: |
          conda activate test-env
          pip install -e ."[dev]" -v
          pip uninstall grpcio; conda install grpcio
      - name: Make Docker
        run: |
          bash ./scripts/make_docker.sh ablator-test
      - name: Test with pytest
        run: |
          conda activate test-env
          pytest --runslow --docker-tag ablator-test
