name: linux-test-mp

on:
  push:
  pull_request:

# TODO remove test_tag="--fast" when flakiness of mp tests is resolved.

jobs:
  pytest:
    runs-on: [self-hosted, ubuntu]
    steps:
    - uses: actions/checkout@v3
    - name: Build Docker
      run: |
        make docker docker_build_args="--py-3-10-12" docker_tag="ablator-test"
    - name: Test with pytest CUDA
      run: |
        make docker-test test_tag="--test-suite mp" docker_build_args="--py-3-10-12" docker_tag="ablator-test"
    - name: Test with pytest CPU
      run: |
        make docker-test-cpu test_tag="--test-suite mp" docker_build_args="--py-3-10-12" docker_tag="ablator-test"
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./shared/coverage_cpu.xml,./shared/coverage_gpu.xml
