name: wsl-test-remote

on:
  push:
  pull_request:

jobs:
  pytest:
    runs-on: [self-hosted, wsl]
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v3
      # - uses: conda-incubator/setup-miniconda@v2
      #   with:
      #     activate-environment: test-env
      #     auto-activate-base: false
      - name: Set up Conda Python 3.10
        run: |
            source $HOME/miniconda3/bin/activate test-env
            conda info