name: wsl-test-remote

on:
  push:
  pull_request:

jobs:
  pytest:
    runs-on: [self-hosted, wsl]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Conda Python 3.10
        run: |
            which conda