name: wsl-test

on:
  push:
  pull_request:

jobs:
  pytest:
    runs-on: [self-hosted, wsl]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Conda Python 3.10
        run: |
            conda remove -y --name test-env --all
            conda create -y -n test-env python=3.10
      - name: Install dependencies
        run: |
          conda activate test-env
          make install
      - name: Make Docker
        run: |
          conda activate test-env
          make docker docker_tag="ablator-test"
      - name: Test with pytest
        run: |
          conda activate test-env
          make test test_tag="--test-suite mp" docker_tag="ablator-test"
